---
- name: ACI QUERY TENANTs
  hosts: aci_demo
  connection: local
  gather_facts: no

  tasks:
  - name: Query all tenants
    aci_tenant:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: query
      validate_certs: no
    delegate_to: localhost
    register: query_result
  - debug:
      msg: "{{ query_result }}"